language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

os:
  - linux
  - osx

install:
  - pip install pep8
  - pip install pep8-naming
  - pip install flake8
  - pip install coverage
  - pip install coveralls

script: sh travis.sh

after_success:
  coveralls
