environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"

os:
  - Visual Studio 2014 CTP4

install:
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\MinGW\\bin;%PATH%"

  - git clone --depth 1 https://github.com/aqualid/aqualid.git
  - "SET PYTHONPATH=%dp0\\aqualid;%PYTHONPATH%;"

build: off

test_script:
  - "python tests\\run.py"
